# Practica 03: Analisis de Datos Exploratorio de Python y Jupiter Notebook

**Programa de Estudios:** Ingieneria en Desarrollo y Gestion de Software \
**Asignatura:** Extraccion conocimientos en bases de datos\
**Docente:** M.T.I. Marco A. Ramirez Hernandez\
**Periodo:** Mayo-Agosto 2026 

**Nombre del Estudiante:** Francisco Garcia Garcia\
**Matricula:** 230758\
**Grado y Grupo:** 9° "A" IDGS

El estudiante practicara como realizar un analisis exploratorio de datos, utilizando el lenguaje de programacion de Python, y librerias comunes para la carga, manipulacion, analisis y visualizacion previa de un conjunto de datos (Dataset), para esta practica se utilizaran las librerias de:
- Pandas
- Numpy
- Seaborn
- os
- Matplotlib

1. importar las librerias necesarias para realizar el EDA
Comenzamos por importar la libreria que nos permita manipular los datos del dataset extraidos de una fuente de datos (datasource)

In [1]:
import pandas as pd

2. Creamos un DataFrame leyendo el archivo delimitado por comas (CSV)

In [2]:
pokemons=pd.read_csv('./Pokemon.csv')

3. Imprimimos el resultado de la lectura
Este comando imprime en una tabla las columnas y las filas del dataframe, siempre de manera eestandar nos mostrara los primero 5 y los 5 registros del dataframe

In [3]:
pokemons

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

4. Obtenemos una muestra aleatoria de resgistros del dataframe usando el metodo sample
Como parametro de entrada podemos definir un entero que determina el tamaño de la muestra

In [4]:
pokemons.sample(6)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
184,170,Chinchou,Water,Electric,330,75,38,38,56,56,67,2,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
373,341,Corphish,Water,NaN,308,43,80,65,50,35,35,3,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
443,398,Staraptor,Normal,Flying,485,85,120,70,50,60,100,4,False
566,507,Herdier,Normal,NaN,370,65,80,65,35,65,60,5,False

## Ejercicio 1: Obten una muestra de 50 pokemones

5. Obtener una muestra de rangos definidos usando **.iloc**

In [5]:
pokemones_100_to_200 = pokemons.iloc[100:200]
pokemones_100_to_200

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
100,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
101,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
103,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False
104,96,Drowzee,Psychic,NaN,328,60,48,45,43,90,42,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,181,Ampharos,Electric,NaN,510,90,75,85,115,90,55,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
197,182,Bellossom,Grass,NaN,490,75,80,95,90,100,50,2,False
198,183,Marill,Water,Fairy,250,70,20,50,20,50,40,2,False
199,184,Azumarill,Water,Fairy,420,100,50,80,60,80,50,2,False

6. Como saber las columnas o atributos tien el data frame

In [6]:
pokemons.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

Campo   Descripción
**#**:  El ID o número de identificación del Pokémon. \
**Name**:   El nombre del Pokémon.\
**Type 1**: Se refiere a las propiedades elementales (tipos) asociadas tanto al Pokémon como a sus movimientos.\
**Type 2**: Los Pokémon pueden tener hasta dos tipos (Pokémon de tipo dual); los movimientos solo pueden tener uno.\
**Total**:  Representa la suma de todos los stats, lo que te da una idea de qué tan "pesado" o fuerte es el Pokémon.\
**HP**: (Puntos de Salud) Es qué tanto aguante tiene un Pokémon antes de que lo dejen fuera de combate (se desmaye).\
**Attack**: La fuerza de los ataques físicos del Pokémon.\
**Defense**:    Qué tanto aguanta el Pokémon contra los ataques físicos del rival.\
**Sp. Atk**:    Ataque Especial; el poder de los movimientos especiales del Pokémon.\
**Sp. Def**:    Defensa Especial; qué tan resistente es el Pokémon ante los ataques especiales.\
**Speed**:  Velocidad; el Pokémon que tenga más velocidad es el que ataca primero.\
**Generation**: Se refiere a la generación de la serie de juegos a la que pertenece.\
**Legendary**:  Indica si el Pokémon es Legendario o no (son bichos muy raros y poderosos). Es un valor booleano (sí/no).

7.- Explorar la composición y ausencia de datos (METADATA) con **.info**
    La libreria de pandas incluye un metodo que nos permite evaluar el tipo de datos, su composicion y ausencia

In [7]:
pokemons.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

8.- Limpieza de datos

Dependiendo del objetivo del analisis algunas columnas o registros no seran necesarias en nuestro dataframe en este caso omitiremos los datos vacios 
eliminaremos la comlumna 'type 2' , y renombremos la columna por 'type 1' por 'type'

In [10]:
pokemons = pokemons.drop(columns=['type 2']).rename(columns={'type 1': 'type'})

KeyError: "['type 2'] not found in axis"

**EJERCICIO 2:** Consulta la METADATA de la actualizacion y compara los cambios con la anterior

¿que datos ves?, redacta tu respuesta

9.- Visualizacion de los primeros datos usando del metodo:  **.head**

In [11]:
pokemons.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

**Ejercicio 3:** Muestra los ultimos 10 registros del dataframe

In [17]:
pokemons.tail(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,Dragon,535,85,70,80,97,80,123,6,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

10.-

In [9]:
pokemons.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

11.- Calcular el total de datos no duplicados (unicos)

Usaremos .len() como función para calcular la longitud del dataframe y .unique() para excluir los duplicados

**NOTA:** No considerar ID como un atributo de llave primaria , sino el total de columnas como un solo elemento u objeto.

Obteniendo los valores unicos por columna en este caso en la columna "Name"

In [13]:
len(pokemons.Name.unique())

800

Obteniento el total de objetos (conjunto de atributos, estrictamente iguales) unicos.

In [14]:
total_unicos = len(pokemons.drop_duplicates())
total_unicos

800

**Ejercicio 04:** Obtener el total de IDs unicos en el dataset

In [15]:
len(pokemons['#'].unique())

721

**Ejercicio 05:** Obtener el total de tipos unicos de pokemones

In [16]:
len(pokemons['Type 1'].unique())

18